const datos = [
  { ciudad: 'Madrid', pais: 'España', humedad: 50, gradosCº: 25, viento: '5 mph' },
  { ciudad: 'Barcelona', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Valencia', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Sevilla', pais: 'España', humedad: 30, gradosCº: 30, viento: '10 mph' },
  { ciudad: 'Zaragoza', pais: 'España', humedad: 45, gradosCº: 28, viento: '6 mph' },
  { ciudad: 'Málaga', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Murcia', pais: 'España', humedad: 35, gradosCº: 29, viento: '5 mph' },
  { ciudad: 'Palma', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Las Palmas de Gran Canaria', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Bilbao', pais: 'España', humedad: 70, gradosCº: 8, viento: '6 mph' },
  { ciudad: 'Alicante', pais: 'España', humedad: 50, gradosCº: 28, viento: '6 mph' },
  { ciudad: 'Córdoba', pais: 'España', humedad: 35, gradosCº: 31, viento: '5 mph' },
  { ciudad: 'Valladolid', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Vitoria', pais: 'España', humedad: 65, gradosCº: 21, viento: '8 mph' },
  { ciudad: 'La Coruña', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Granada', pais: 'España', humedad: 30, gradosCº: 32, viento: '10 mph' },
  { ciudad: 'Gijón', pais: 'España', humedad: 70, gradosCº: 20, viento: '6 mph' },
  { ciudad: 'Lugo', pais: 'España', humedad: 80, gradosCº: 18, viento: '5 mph' },
  { ciudad: 'Toledo', pais: 'España', humedad: 45, gradosCº: 28, viento: '6 mph' },
  { ciudad: 'Santander', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Pamplona', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Oviedo', pais: 'España', humedad: 70, gradosCº: 20, viento: '6 mph' },
  { ciudad: 'Melilla', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Mérida', pais: 'España', humedad: 35, gradosCº: 29, viento: '5 mph' },
  { ciudad: 'Ceuta', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Badajoz', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Logroño', pais: 'España', humedad: 65, gradosCº: 21, viento: '8 mph' },
  { ciudad: 'Tarragona', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'León', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Huelva', pais: 'España', humedad: 80, gradosCº: 18, viento: '5 mph' },
  { ciudad: 'Almería', pais: 'España', humedad: 45, gradosCº: 28, viento: '6 mph' },
  { ciudad: 'Salamanca', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Guadalajara', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Cáceres', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Segovia', pais: 'España', humedad: 65, gradosCº: 21, viento: '8 mph' },
  { ciudad: 'Ávila', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Cuenca', pais: 'España', humedad: 80, gradosCº: 18, viento: '5 mph' },
  { ciudad: 'Soria', pais: 'España', humedad: 80, gradosCº: 18, viento: '5 mph' },
  { ciudad: 'Huesca', pais: 'España', humedad: 65, gradosCº: 21, viento: '8 mph' },
  { ciudad: 'Teruel', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Palencia', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Jaén', pais: 'España', humedad: 30, gradosCº: 32, viento: '10 mph' },
  { ciudad: 'Albacete', pais: 'España', humedad: 45, gradosCº: 28, viento: '6 mph' },
  { ciudad: 'Burgos', pais: 'España', humedad: 65, gradosCº: 10, viento: '8 mph' },
  { ciudad: 'Cádiz', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Castellón de la Plana', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Ciudad Real', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Ourense', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Santiago de Compostela', pais: 'España', humedad: 80, gradosCº: 18, viento: '5 mph' },
  { ciudad: 'Pontevedra', pais: 'España', humedad: 80, gradosCº: 18, viento: '5 mph' },
  { ciudad: 'Vigo', pais: 'España', humedad: 70, gradosCº: 20, viento: '6 mph' },
  { ciudad: 'Ferrol', pais: 'España', humedad: 75, gradosCº: 19, viento: '9 mph' },
  { ciudad: 'Santa Cruz de Tenerife', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Santa Coloma de Gramenet', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Badalona', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Sabadell', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Mataró', pais: 'España', humedad: 60, gradosCº: 22, viento: '8 mph' },
  { ciudad: 'Elche', pais: 'España', humedad: 50, gradosCº: 28, viento: '6 mph' },
  { ciudad: 'Torrevieja', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Orihuela', pais: 'España', humedad: 35, gradosCº: 29, viento: '5 mph' },
  { ciudad: 'Marbella', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Estepona', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Benalmádena', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Fuengirola', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Cartagena', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Alcantarilla', pais: 'España', humedad: 55, gradosCº: 24, viento: '7 mph' },
  { ciudad: 'Lorca', pais: 'España', humedad: 35, gradosCº: 29, viento: '5 mph' },
  { ciudad: 'Mazarrón', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Águilas', pais: 'España', humedad: 65, gradosCº: 27, viento: '9 mph' },
  { ciudad: 'Inca', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Manacor', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Alcúdia', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Calvià', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Llucmajor', pais: 'España', humedad: 60, gradosCº: 26, viento: '8 mph' },
  { ciudad: 'Telde', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Arrecife', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Puerto del Rosario', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Arucas', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Mogán', pais: 'España', humedad: 70, gradosCº: 15, viento: '10 mph' },
  { ciudad: 'Santa Lucía de Tirajana', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Telde', pais: 'España', humedad: 70, gradosCº: 8, viento: '10 mph' },
  { ciudad: 'Arrecife', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Puerto del Rosario', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Arucas', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Mogán', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Santa Lucía de Tirajana', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Tías', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'San Bartolomé de Tirajana', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Agüimes', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Ingenio', pais: 'España', humedad: 70, gradosCº: 24, viento: '10 mph' },
  { ciudad: 'Gáldar', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Santa María de Guía de Gran Canaria', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Mogán', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Pájara', pais: 'España', humedad: 70, gradosCº: 19, viento: '10 mph' },
  { ciudad: 'Antigua', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'La Oliva', pais: 'España', humedad: 70, gradosCº: 12, viento: '10 mph' },
  { ciudad: 'Betancuria', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Tuineje', pais: 'España', humedad: 70, gradosCº: 20, viento: '10 mph' },
  { ciudad: 'Pájara', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Antigua', pais: 'España', humedad: 70, gradosCº: 13, viento: '10 mph' },
  { ciudad: 'La Oliva', pais: 'España', humedad: 70, gradosCº: 25, viento: '10 mph' },
  { ciudad: 'Betancuria', pais: 'España', humedad: 70, gradosCº: 23, viento: '10 mph' },
  { ciudad: 'Tuineje', pais: 'España', humedad: 70, gradosCº: 16, viento: '10 mph' }
]

export default datos;